const DependenciesManager = require('../index');
const TypesFactory = require('@ah/metadata-factory');
const { FileWriter } = require('@ah/core').FileSystem;
const { MetadataType, MetadataObject, MetadataItem } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

describe('Testing ./index.js', () => {
    test('Testing repairDependencies()', () => {
        const metadataDetails = TypesFactory.createMetadataDetails('./test/assets/metadataTypes.json');
        FileWriter.copyFolderSync('./test/assets/SFDXProject', './test/assets/SFDXProjectCopy', true);
        FileWriter.delete('./test/assets/SFDXProjectCopy/force-app/main/default/flexipages/PA_lightRp_servicios.flexipage-meta.xml');
        FileWriter.delete('./test/assets/SFDXProjectCopy/force-app/main/default/profiles/Account Manager.profile-meta.xml');
        FileWriter.delete('./test/assets/SFDXProjectCopy/force-app/main/default/tabs/o_guias_precios__c.tab-meta.xml');
        FileWriter.delete('./test/assets/SFDXProjectCopy/force-app/main/default/tabs/o_domains__c.tab-meta.xml');
        FileWriter.delete('./test/assets/SFDXProjectCopy/force-app/main/default/tabs/o_bonificaciones__c.tab-meta.xml');
        DependenciesManager.getSupportedTypes();
        const manager = new DependenciesManager('./test/assets/SFDXProjectCopy', metadataDetails);
        manager.setCompress(true);
        manager.setIgnoreFile('./test/assets/SFDXProjectCopy/.ahignore.json');
        let errors = manager.checkErrors();
        //console.log(JSON.stringify(errors, null, 2));
        manager.setCompress(false);
        manager.setIgnoreFile(undefined);
        manager.repairDependencies('./test/assets/SFDXProjectCopy', metadataDetails);
        manager.setCompress(true);
        manager.setIgnoreFile('./test/assets/SFDXProjectCopy/.ahignore.json');
        errors = manager.repairDependencies();
        const types = {};
        types[MetadataTypes.PERMISSION_SET] = new MetadataType(MetadataTypes.PERMISSION_SET, false);
        types[MetadataTypes.PERMISSION_SET].addChild(new MetadataObject('permission', true));
        types['Profilesss']  = new MetadataType('Profilesss', false);
        types['Profilesss'].addChild(new MetadataObject('permission', true));
        types['CustomFields'] = new MetadataType('CustomFields', true);
        types['Labels'] = new MetadataType('Labels', true);
        manager.setCompress(true);
        manager.setIgnoreFile('./test/assets/SFDXProjectCopy/.ahignore.json');
        manager.sortSimpleFirst();
        manager.setTypesToRepair(types);
        manager.repairDependencies();
        //console.log(JSON.stringify(errors, null, 2));
    });
});